version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: development
    image: hero99challenge/backend-dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3500:3500"
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: development
    image: hero99challenge/frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend


