version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: production
    image: hero99challenge/backend-production
    ports:
      - "80:80"

  frontend:
    build:
      context: ./frontend
      target: production
    image: hero99challenge/frontend-production
    ports:
      - "80:80"
